import { K6sConfigSchema, type K6sConfig } from '../models/config.js';

export function createSecurityStrictConfig(projectName: string): K6sConfig {
  return K6sConfigSchema.parse({
    version: '1',
    project: {
      name: projectName,
      description: 'Strict security posture with defensive boundaries.',
    },
    session: {
      context_retention_days: 365,
      audit_retention_days: 730,
      session_retention_days: 730,
      end_on_claude_exit: true,
    },
    boundaries: [
      {
        pattern: '*',
        forbidden_paths: [
          '.env*',
          '**/.env*',
          '**/secrets/**',
          '**/credentials/**',
          '**/*.pem',
          '**/*.key',
          '**/*.crt',
          '**/*.p12',
          '**/*.pfx',
          '**/id_rsa*',
          '**/id_ed25519*',
          '**/auth/**',
          '**/security/**',
          '**/.github/workflows/**',
          '**/docker-compose*.yml',
          '**/docker-compose*.yaml',
          '**/Dockerfile*',
          '**/k8s/**',
          '**/kubernetes/**',
          '**/helm/**',
          '**/terraform/**',
          '**/*.tf',
          '**/*.tfvars',
          '**/deploy/**',
          '**/deployment/**',
          '**/infra/**',
          '**/.claude/**',
          '.khoregos/**',
        ],
        enforcement: 'strict',
        max_tool_calls_per_session: 120,
      },
    ],
    gates: [
      {
        id: 'dependency-approval',
        name: 'Dependency and lockfile changes',
        trigger: {
          file_patterns: [
            'package.json',
            'pnpm-lock.yaml',
            'package-lock.json',
            'yarn.lock',
            'requirements.txt',
            'poetry.lock',
            'Pipfile',
            'Pipfile.lock',
            'go.mod',
            'go.sum',
            'Cargo.toml',
            'Cargo.lock',
            '**/pom.xml',
            '**/build.gradle',
          ],
        },
        approval_mode: 'manual',
        timeout_seconds: 1800,
        notify: ['terminal'],
      },
      {
        id: 'security-files',
        name: 'Security and secret material changes',
        trigger: {
          file_patterns: [
            '.env*',
            '**/secrets/**',
            '**/credentials/**',
            '**/*.pem',
            '**/*.key',
            '**/*.crt',
            '**/*.p12',
            '**/*.pfx',
            '**/auth/**',
            '**/security/**',
          ],
        },
        approval_mode: 'manual',
        timeout_seconds: 1800,
        notify: ['terminal'],
      },
      {
        id: 'infrastructure-files',
        name: 'Infrastructure and deployment changes',
        trigger: {
          file_patterns: [
            '**/.github/workflows/**',
            '**/docker-compose*.yml',
            '**/docker-compose*.yaml',
            '**/Dockerfile*',
            '**/k8s/**',
            '**/kubernetes/**',
            '**/helm/**',
            '**/terraform/**',
            '**/*.tf',
            '**/*.tfvars',
            '**/deploy/**',
            '**/deployment/**',
            '**/infra/**',
          ],
        },
        approval_mode: 'manual',
        timeout_seconds: 1800,
        notify: ['terminal'],
      },
    ],
    observability: {
      prometheus: { enabled: false, port: 9090 },
      opentelemetry: { enabled: false, endpoint: 'http://localhost:4317' },
      webhooks: [],
    },
    plugins: [],
  });
}
